dist: trusty
sudo: false
language: php
php:
- '5.5'
services:
- mysql
install:
- mysql -e 'CREATE DATABASE aurora;'
- composer install
- npm install -g newman
script:
- php ./travis.php
- chmod +x ./travis.sh
- ./travis.sh -t build
after_success: 
- ./travis.sh -t upload
env:
  global:
  - PRODUCT_NAME=webmail-lite
  - secure: Grnewi7CZWM9V3l/jF0/AEU+sv1NJKP+7hC8cTSqeST9o2qSZjVTjp03W6Y2uCgC8rjezVozGVDjSUkvaJnAXfS3aIrXaRvPkuHIW167lpV1cpoaaaxZwQi9as+IuhmE0YgPSdcjagNJdS1HRqszcd1RjWbgnqEPz6/DKwPFZA1d1fG8XUSIRsZLJeBCNBz2puYZVaYBAHEDV/lrur5exKOJYNvLMRgDijrvj+nL0i49+6apzuBURCMbnV1TewDliA0y76/qvGpmJ/IJYixUNV52ThpUCYKkoecM4UIWpDOJYP60x/PD+uP+FpA3PXspVIjUcyCYNW1vatzZO3S10S+/v7EIZPrwlKa6a7346doEmPmTOkLbL45r6WmeJtXV8bkIvBsnGFMBjb9CpDbEjGy2RrARwFO6jocdPa8K+1QOxvekgHGJJmJV7dxwGFw1HGBnjjFFH3CfnVeTPkSnz0kgynvnWh0tbGxxro3lpo5GSQbmQgPYu+s+nKan45jIGMUAxe2XnezzD99olToOZaTTrZ0rKGpjtlvMWQwQKTEpqE1mIeXFRbdJpDyikAafh33OTnJuN2mkK29Q72elw75LgOm0hUSE67mjAzN21Rvnxuy9M1JKtUi/40IdM6YK7oQv+Y1PqnXlTAhtMQc3ag3cJdECn6Gn2B64e71nzC0=
  - secure: QJuQ2ujzK8VB0Z8LrYhHf+R5iRQF/fJk4rY4+frsdZo3aX34kNdGyUjcX9LV3TeERn6sAX/C/XfXQgJTXTg4Sk/HTxvAONi/0YWmiruRYC6kT6J+JkIlUIsT5w3lTahbtAww2znzDvs7cb7MyMlXv9sfnLzJtXW+R8e8VYWNba5zRU3cE7JljgRG6iNfqSD/DRueUPnJVQRKWaQZNSwxeDgMb+DpOeycf9RyGg3ayb5/DQ7lRct3ChTABNjpAEMH76kGwDiCgAXpNyTXn11GZFGKLDiXMsTH5V7GOMBjtp20As+SgGi02WyVBr42WSDQ5VvcYicErHfNSHg58TyZDTzWswDeyVE5fB1tfBNiePbg5pwApJMkxMvS5dqbx36eq60owkQPfpjcJl+41hsynuWaw5O+kTUZ4DGsjLvlg5xOHsP55IIJnHmbdynnd8+fiJF0/FET1e2s9ocgsWnrGzVJ4WnoBOTnYYapvd/lIE4YT2nPeMQl77IMI5fOqSsDpcSfJtrsk/mPSQc6dSnjtKAX+2YLykh830unbU4MiiwyKAdXmN/VrYjq3BkoRY8+JaqilMbGq6YWrFnp8Cz6CLAiKjKCW34PDlUZjAHVFGNnW2Vm2o4xdWh92Z6MwNb7i3XVVp6PSBoeP5foGUv/4kgiBXIEysJrU/YI4+0pktQ=
